/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eduar
 */
public class Mercado_GUI extends javax.swing.JFrame {
public static int contBook = 0;
public static int contCourses = 0;
    public Mercado_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        book1 = new javax.swing.JButton();
        book2 = new javax.swing.JButton();
        book3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        curso1 = new javax.swing.JButton();
        curso2 = new javax.swing.JButton();
        curso3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton1.setText("menu sand");
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 10, 90, 23);

        jButton2.setText("lupa(pesquisar)");
        jPanel1.add(jButton2);
        jButton2.setBounds(296, 11, 110, 23);

        jButton3.setText("perfil");
        jPanel1.add(jButton3);
        jButton3.setBounds(408, 11, 70, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(null);

        jLabel1.setText("Como ter");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 17);

        jLabel2.setText("<html>TANQU<br>INHO </html>");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 30, 70, 30);

        jLabel3.setText("em");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 50, 18, 17);

        jLabel4.setText("1 SEMANA");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 17);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(60, 20, 80, 90);

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));
        jPanel6.setLayout(null);
        jPanel2.add(jPanel6);
        jPanel6.setBounds(150, 20, 80, 90);

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setLayout(null);
        jPanel2.add(jPanel7);
        jPanel7.setBounds(240, 20, 80, 90);

        book1.setText("Comprar");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel2.add(book1);
        book1.setBounds(60, 120, 79, 23);

        book2.setText("Comprar");
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        jPanel2.add(book2);
        book2.setBounds(160, 120, 79, 23);

        book3.setText("Comprar");
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        jPanel2.add(book3);
        book3.setBounds(250, 120, 79, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 50, 500, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));
        jPanel8.setLayout(null);
        jPanel3.add(jPanel8);
        jPanel8.setBounds(60, 20, 80, 100);

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setLayout(null);
        jPanel3.add(jPanel9);
        jPanel9.setBounds(160, 20, 80, 100);

        jPanel10.setBackground(new java.awt.Color(255, 153, 102));
        jPanel10.setLayout(null);
        jPanel3.add(jPanel10);
        jPanel10.setBounds(260, 20, 80, 100);

        curso1.setText("jButton8");
        curso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso1ActionPerformed(evt);
            }
        });
        jPanel3.add(curso1);
        curso1.setBounds(60, 130, 78, 23);

        curso2.setText("Comprar");
        curso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso2ActionPerformed(evt);
            }
        });
        jPanel3.add(curso2);
        curso2.setBounds(160, 130, 79, 23);

        curso3.setText("Comprar");
        curso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso3ActionPerformed(evt);
            }
        });
        jPanel3.add(curso3);
        curso3.setBounds(260, 130, 79, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 200, 500, 160);

        jButton4.setText("Voltar");
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 370, 72, 23);

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setLayout(null);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(130, 10, 166, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 500, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void curso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso1ActionPerformed
        contCourses = 1;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso1ActionPerformed

    private void curso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso3ActionPerformed
        contCourses = 3;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso3ActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
       contBook = 1;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book1ActionPerformed

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        contBook = 2;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book2ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
       contBook = 3;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book3ActionPerformed

    private void curso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso2ActionPerformed
       contCourses = 2;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercado_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book1;
    private javax.swing.JButton book2;
    private javax.swing.JButton book3;
    private javax.swing.JButton curso1;
    private javax.swing.JButton curso2;
    private javax.swing.JButton curso3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
