/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eduar
 */
public class Mercado_GUI extends javax.swing.JFrame {
public static int contBook = 0;
public static int contCourses = 0;
public static int aparece2 = 1;
    public Mercado_GUI() {
        initComponents();
        painelMenuSand.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelMenuSand = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        book1 = new javax.swing.JButton();
        book2 = new javax.swing.JButton();
        book3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botaoSand = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        curso1 = new javax.swing.JButton();
        curso2 = new javax.swing.JButton();
        curso3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(103, 179, 179));
        jPanel1.setLayout(null);

        painelMenuSand.setBackground(new java.awt.Color(255, 255, 255));
        painelMenuSand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 179, 179), 2));
        painelMenuSand.setLayout(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jButton5.setText(" Início");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton5);
        jButton5.setBounds(10, 10, 110, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maisReceitas.png"))); // NOI18N
        jButton6.setText(" Receitas");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton6);
        jButton6.setBounds(10, 40, 110, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/valorNutri.png"))); // NOI18N
        jButton7.setText(" Nutrição");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton7);
        jButton7.setBounds(10, 100, 110, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculadora.png"))); // NOI18N
        jButton8.setText("Met. Basal");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton8);
        jButton8.setBounds(10, 70, 110, 30);

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        jButton9.setText("  Sair");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton9);
        jButton9.setBounds(10, 130, 110, 30);

        jPanel1.add(painelMenuSand);
        painelMenuSand.setBounds(10, 40, 130, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ebook1_1.png"))); // NOI18N
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 0, 60, 90);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(60, 20, 80, 90);

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));
        jPanel6.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ebook2.png"))); // NOI18N
        jPanel6.add(jLabel1);
        jLabel1.setBounds(10, 0, 63, 90);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(210, 20, 80, 90);

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ebook3.png"))); // NOI18N
        jPanel7.add(jLabel2);
        jLabel2.setBounds(20, 0, 70, 90);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(360, 20, 90, 90);

        book1.setText("Comprar");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel2.add(book1);
        book1.setBounds(53, 120, 80, 23);

        book2.setText("Comprar");
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        jPanel2.add(book2);
        book2.setBounds(210, 120, 80, 23);

        book3.setText("Comprar");
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        jPanel2.add(book3);
        book3.setBounds(360, 120, 90, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 50, 500, 150);

        jButton4.setText("Voltar");
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 370, 61, 23);

        jPanel4.setBackground(new java.awt.Color(103, 179, 179));
        jPanel4.setLayout(null);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(80, 10, 320, 30);

        jButton3.setBackground(new java.awt.Color(103, 179, 179));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconePerfil (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(450, 0, 50, 50);

        jButton2.setBackground(new java.awt.Color(103, 179, 179));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        jPanel4.add(jButton2);
        jButton2.setBounds(400, 10, 40, 30);

        botaoSand.setBackground(new java.awt.Color(103, 179, 179));
        botaoSand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        botaoSand.setBorderPainted(false);
        botaoSand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSandActionPerformed(evt);
            }
        });
        jPanel4.add(botaoSand);
        botaoSand.setBounds(10, 0, 50, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 500, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));
        jPanel8.setLayout(null);

        jLabel3.setText("Aqui");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(20, 44, 70, 20);

        jLabel4.setText("+ Cursos");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(10, 20, 70, 20);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(60, 20, 80, 100);

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setLayout(null);

        jLabel7.setText("Aqui");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(30, 40, 70, 20);

        jLabel6.setText("+ Cursos");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(20, 10, 70, 20);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(210, 20, 90, 100);

        jPanel10.setBackground(new java.awt.Color(255, 153, 102));
        jPanel10.setLayout(null);

        jLabel8.setText("+ Cursos");
        jPanel10.add(jLabel8);
        jLabel8.setBounds(20, 10, 70, 20);

        jLabel9.setText("Aqui");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(30, 40, 70, 20);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(370, 20, 80, 100);

        curso1.setText("Comprar");
        curso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso1ActionPerformed(evt);
            }
        });
        jPanel3.add(curso1);
        curso1.setBounds(60, 130, 80, 23);

        curso2.setText("Comprar");
        curso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso2ActionPerformed(evt);
            }
        });
        jPanel3.add(curso2);
        curso2.setBounds(200, 130, 100, 23);

        curso3.setText("Comprar");
        curso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso3ActionPerformed(evt);
            }
        });
        jPanel3.add(curso3);
        curso3.setBounds(360, 130, 90, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 200, 500, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void curso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso1ActionPerformed
        contCourses = 1;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso1ActionPerformed

    private void curso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso3ActionPerformed
        contCourses = 3;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso3ActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
       contBook = 1;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book1ActionPerformed

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        contBook = 2;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book2ActionPerformed

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
       contBook = 3;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_book3ActionPerformed

    private void curso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso2ActionPerformed
       contCourses = 2;
       try{
        Model.Mercado_DAO.ebooks();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_curso2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Perfil_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botaoSandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSandActionPerformed
        aparece2++;
        if(aparece2%2 == 0){
            painelMenuSand.setVisible(true);
        }else{
            painelMenuSand.setVisible(false);      
        }
    }//GEN-LAST:event_botaoSandActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Home_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Receitas_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new ValorNutricional_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new MetabolismoBasal_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercado_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercado_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book1;
    private javax.swing.JButton book2;
    private javax.swing.JButton book3;
    private javax.swing.JButton botaoSand;
    private javax.swing.JButton curso1;
    private javax.swing.JButton curso2;
    private javax.swing.JButton curso3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel painelMenuSand;
    // End of variables declaration//GEN-END:variables
}
