/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author eduar
 */
public class MetabolismoBasal_GUI extends javax.swing.JFrame {
    public static int aparece = 1;
    /**
     * Creates new form MetabolismoBasal_GUI
     */
    public MetabolismoBasal_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(null);

        jButton1.setText("Menu sand");
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 10, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cálculo de Metabolismo Basal");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 10, 190, 14);

        jButton2.setText("perfil");
        jPanel2.add(jButton2);
        jButton2.setBounds(410, 10, 57, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 40);

        jLabel1.setText("Metabolismo basal ou Taxa metabólica basal é um método matemático, não exato, de");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 470, 14);

        jLabel3.setText("calcular a quantidade calórica que o corpo necessita, em vinte e quatro horas,");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 470, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("O que é:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 60, 15);

        jLabel5.setText("para manter-se nutrido durante o decorrer das atividades diárias, e/ou fazendo um");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 110, 460, 14);

        jLabel6.setText("jejum de pelo menos doze horas em repouso, sem prejudicar o funcionamento dos");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 130, 460, 14);

        jLabel7.setText("principais órgão e manter a temperatura corporal sobre a normalidade.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 150, 450, 14);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cálculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jLabel10.setText("Peso (Kg):");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 30, 70, 14);

        jLabel11.setText("Idade:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 90, 50, 14);

        jLabel12.setText("Altura (cm):");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 60, 70, 14);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(100, 30, 90, 20);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(100, 60, 90, 20);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(100, 90, 90, 20);

        jLabel13.setText("Sexo:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 120, 28, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(100, 120, 90, 20);

        jButton3.setText("Calcular");
        jPanel3.add(jButton3);
        jButton3.setBounds(260, 113, 140, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Resultado:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(300, 20, 70, 20);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("- - -");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(290, 50, 80, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 230, 450, 160);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setText("Fórmula");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(380, 180, 90, 40);

        jLabel8.setText("Homens: 66x+ (13,7 x Peso) + (5,0 x Altura) - (6,8 x Idade)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 180, 310, 14);

        jLabel9.setText("Mulheres: 665 + (9,6 x Peso) + (1,8 x Altura) - (4,7 x Idade)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 200, 310, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetabolismoBasal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetabolismoBasal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetabolismoBasal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetabolismoBasal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetabolismoBasal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
