/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.awt.GraphicsConfiguration;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class Receitas_GUI extends javax.swing.JFrame {
    public static int receitas = 0;
    public static int aparece2 = 1;
    
    public Receitas_GUI(GraphicsConfiguration gc) {
        super(gc);
    }

    /**
     * Creates new form Receitas_GUI
     */
    public Receitas_GUI() {
        initComponents();
        painelMenuSand.setVisible(false);
        painel1.setVisible(true);
        painel2.setVisible(true);
        painel3.setVisible(true);
        painel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        painel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoSand = new javax.swing.JButton();
        painelMenuSand = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        pesquisa = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        painel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        painel4.setBackground(new java.awt.Color(255, 255, 255));
        painel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 139, 30)));
        painel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Frango frito");
        painel4.add(jLabel13);
        jLabel13.setBounds(10, 11, 110, 20);

        jLabel14.setText("Uma receita ideal para quem tem pouco tempo");
        painel4.add(jLabel14);
        jLabel14.setBounds(10, 50, 240, 14);

        jButton1.setText("Fazer");
        painel4.add(jButton1);
        jButton1.setBounds(380, 10, 60, 60);

        jLabel15.setText("Preço estimado: R$ 30");
        painel4.add(jLabel15);
        jLabel15.setBounds(250, 10, 120, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        botaoSand.setBackground(new java.awt.Color(255, 139, 30));
        botaoSand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        botaoSand.setBorderPainted(false);
        botaoSand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSandActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSand);
        botaoSand.setBounds(10, 10, 50, 50);

        painelMenuSand.setBackground(new java.awt.Color(255, 255, 255));
        painelMenuSand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 133, 34), 2));
        painelMenuSand.setLayout(null);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jButton7.setText(" Início");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton7);
        jButton7.setBounds(10, 10, 110, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculadora.png"))); // NOI18N
        jButton8.setText("Met. Basal");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton8);
        jButton8.setBounds(10, 40, 110, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/valorNutri.png"))); // NOI18N
        jButton9.setText(" Nutrição");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton9);
        jButton9.setBounds(10, 100, 110, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mercado.png"))); // NOI18N
        jButton10.setText(" Mercado");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton10);
        jButton10.setBounds(10, 70, 110, 30);

        jButton11.setBackground(new java.awt.Color(255, 51, 51));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        jButton11.setText("  Sair");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        painelMenuSand.add(jButton11);
        jButton11.setBounds(10, 130, 110, 30);

        jPanel1.add(painelMenuSand);
        painelMenuSand.setBounds(10, 60, 130, 170);
        jPanel1.add(pesquisa);
        pesquisa.setBounds(80, 20, 320, 30);

        pesquisar.setBackground(new java.awt.Color(255, 255, 255));
        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisar);
        pesquisar.setBounds(390, 20, 40, 30);

        jButton13.setBackground(new java.awt.Color(255, 139, 30));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconePerfil (1).png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(440, 10, 50, 50);

        painel3.setBackground(new java.awt.Color(255, 255, 255));
        painel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 139, 30)));
        painel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Smoothie de Morange e Banana");
        painel3.add(jLabel9);
        jLabel9.setBounds(10, 0, 230, 30);

        jLabel10.setText("Você só precisa de duas frutas, iogurte e gelo para fazer");
        painel3.add(jLabel10);
        jLabel10.setBounds(10, 40, 350, 14);

        jButton6.setBackground(new java.awt.Color(255, 139, 30));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Fazer");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        painel3.add(jButton6);
        jButton6.setBounds(369, 20, 70, 40);

        jLabel12.setText("essa bebida nutritiva e saborosa");
        painel3.add(jLabel12);
        jLabel12.setBounds(10, 60, 300, 14);

        jLabel16.setText("Preço: R$20");
        painel3.add(jLabel16);
        jLabel16.setBounds(260, 10, 120, 14);

        jPanel1.add(painel3);
        painel3.setBounds(20, 290, 450, 90);

        painel2.setBackground(new java.awt.Color(255, 255, 255));
        painel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 139, 30)));
        painel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pão de Queijo de Frigideira");
        painel2.add(jLabel4);
        jLabel4.setBounds(10, 0, 220, 30);

        jLabel6.setText("Uma receita simples e cheia de proteínas");
        painel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 250, 14);

        jButton5.setBackground(new java.awt.Color(255, 139, 30));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Fazer");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        painel2.add(jButton5);
        jButton5.setBounds(370, 20, 70, 40);

        jLabel17.setText("Preço: R$30");
        painel2.add(jLabel17);
        jLabel17.setBounds(260, 10, 120, 14);

        jPanel1.add(painel2);
        painel2.setBounds(20, 190, 450, 90);

        painel1.setBackground(new java.awt.Color(255, 255, 255));
        painel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 139, 30)));
        painel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mingau de Tapioca sem Açúcar");
        painel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 220, 30);

        jLabel2.setText("A tapioca é uma receita leve, e ao mesmo tempo saborosa");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        painel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 350, 20);

        jButton4.setBackground(new java.awt.Color(255, 139, 30));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Fazer");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        painel1.add(jButton4);
        jButton4.setBounds(370, 20, 70, 40);

        jLabel8.setText(" essa receita promete adicionar um pouco de sabor a ela");
        painel1.add(jLabel8);
        jLabel8.setBounds(10, 60, 340, 14);

        jLabel11.setText("Preço: R$15");
        painel1.add(jLabel11);
        jLabel11.setBounds(260, 10, 120, 14);

        jPanel1.add(painel1);
        painel1.setBounds(20, 80, 450, 100);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        receitas = 1;
        try{
        Model.Receitas_DAO.receitas();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        receitas = 2;
        try{
        Model.Receitas_DAO.receitas();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        receitas = 3;
        try{
        Model.Receitas_DAO.receitas();
    }catch(Exception ex){
            Logger.getLogger(Mercado_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void botaoSandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSandActionPerformed
        aparece2++;
        if(aparece2%2 == 0){
            painelMenuSand.setVisible(true);
        }else{
            painelMenuSand.setVisible(false);
        }
    }//GEN-LAST:event_botaoSandActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Home_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new MetabolismoBasal_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new ValorNutricional_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new Mercado_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new Perfil_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        /*String pes = pesquisa.getText(); 
        if(pes.equals("Frago")){
            JOptionPane.showMessageDialog(null, "Frango");
            painel1.setVisible(false);
            painel2.setVisible(false);
            painel3.setVisible(false);
            painel4.setVisible(true);
        }*/
        
    }//GEN-LAST:event_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receitas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receitas_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSand;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painelMenuSand;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JButton pesquisar;
    // End of variables declaration//GEN-END:variables
}
